# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'binsmart' do
pod 'MQTTClient'
pod 'MQTTClient/Websocket'
end

target 'binsmartTests' do

end

target 'binsmartUITests' do

end

